name: Hourly Update and Push

on:
    # Execute this workflow every 2 hours
    schedule:
        - cron: "0 */2 * * *"
    # Allows you to trigger manually from GitHub's Actions tab
    workflow_dispatch:

jobs:
    updateAndPush:
        runs-on: ubuntu-latest

        permissions:
            contents: write

        env:
            NETWORK: ${{ vars.NETWORK }}
            PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
            RECIPIENT: ${{ vars.RECIPIENT }}
            FLOW_ADDRESS: ${{ vars.FLOW_ADDRESS }}
            FLOW_PRIVATE_KEY: ${{ secrets.FLOW_PRIVATE_KEY }}
            TESTNET_ALCHEMY_URL: ${{ secrets.TESTNET_ALCHEMY_URL }}
            MAINNET_ALCHEMY_URL: ${{ secrets.MAINNET_ALCHEMY_URL }}

        steps:
            - uses: actions/checkout@v4
              with:
                ref: main

            - uses: oven-sh/setup-bun@v2

            - name: Install Dependencies
              run: bun install

            - name: Run the output generation
              run: bun start

            - name: Commit all updates
              uses: stefanzweifel/git-auto-commit-action@v5
              with:
                commit_message: "chore: update latency results."
                branch: main
                file_pattern: "outputs/*.*"
                commit_author: "GitHub Action <actions@github.com>"
